package sample_java_server;
//package MyJavaDemo;

import java.io.IOException;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import user.UserService;


public class App {
	
	public static void main(String[] args) throws IOException, InterruptedException {
		
		Server server = ServerBuilder.forPort(50100).addService(new UserService()).build();

		System.out.println("Starting server...");
		server.start();
		System.out.println("Server started");
		
		server.awaitTermination();
		System.out.println("Server terminated");
	}

    public String getGreeting() {
        return "Hello world.";
    }

}




/*
 * This Java source file was generated by the Gradle 'init' task.
package MyJavaDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
 */

