// source: resource_mgr.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.resourceMgr.CmdReserveResource', null, global);
goog.exportSymbol('proto.resourceMgr.CmdSendRequest', null, global);
goog.exportSymbol('proto.resourceMgr.CmdUpdateStatus', null, global);
goog.exportSymbol('proto.resourceMgr.ResmgrCmd', null, global);
goog.exportSymbol('proto.resourceMgr.ResmgrCmd.PayloadCase', null, global);
goog.exportSymbol('proto.resourceMgr.ResmgrMsgType', null, global);
goog.exportSymbol('proto.resourceMgr.ResmgrRsp', null, global);
goog.exportSymbol('proto.resourceMgr.ResmgrRsp.PayloadCase', null, global);
goog.exportSymbol('proto.resourceMgr.RspReserveResource', null, global);
goog.exportSymbol('proto.resourceMgr.RspSendRequest', null, global);
goog.exportSymbol('proto.resourceMgr.RspUpdateStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.ResmgrCmd = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.resourceMgr.ResmgrCmd.oneofGroups_);
};
goog.inherits(proto.resourceMgr.ResmgrCmd, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.ResmgrCmd.displayName = 'proto.resourceMgr.ResmgrCmd';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.ResmgrRsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.resourceMgr.ResmgrRsp.oneofGroups_);
};
goog.inherits(proto.resourceMgr.ResmgrRsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.ResmgrRsp.displayName = 'proto.resourceMgr.ResmgrRsp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdSendRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdSendRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.CmdSendRequest.displayName = 'proto.resourceMgr.CmdSendRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspSendRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspSendRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.RspSendRequest.displayName = 'proto.resourceMgr.RspSendRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdReserveResource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdReserveResource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.CmdReserveResource.displayName = 'proto.resourceMgr.CmdReserveResource';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspReserveResource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspReserveResource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.RspReserveResource.displayName = 'proto.resourceMgr.RspReserveResource';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdUpdateStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdUpdateStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.CmdUpdateStatus.displayName = 'proto.resourceMgr.CmdUpdateStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspUpdateStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspUpdateStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resourceMgr.RspUpdateStatus.displayName = 'proto.resourceMgr.RspUpdateStatus';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resourceMgr.ResmgrCmd.oneofGroups_ = [[3,4,5]];

/**
 * @enum {number}
 */
proto.resourceMgr.ResmgrCmd.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  CMDSENDREQUEST: 3,
  CMDRESERVERESOURCE: 4,
  CMDUPDATESTATUS: 5
};

/**
 * @return {proto.resourceMgr.ResmgrCmd.PayloadCase}
 */
proto.resourceMgr.ResmgrCmd.prototype.getPayloadCase = function() {
  return /** @type {proto.resourceMgr.ResmgrCmd.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.resourceMgr.ResmgrCmd.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.ResmgrCmd.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.ResmgrCmd.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.ResmgrCmd} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.ResmgrCmd.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    responsequeue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cmdsendrequest: (f = msg.getCmdsendrequest()) && proto.resourceMgr.CmdSendRequest.toObject(includeInstance, f),
    cmdreserveresource: (f = msg.getCmdreserveresource()) && proto.resourceMgr.CmdReserveResource.toObject(includeInstance, f),
    cmdupdatestatus: (f = msg.getCmdupdatestatus()) && proto.resourceMgr.CmdUpdateStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.ResmgrCmd}
 */
proto.resourceMgr.ResmgrCmd.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.ResmgrCmd;
  return proto.resourceMgr.ResmgrCmd.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.ResmgrCmd} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.ResmgrCmd}
 */
proto.resourceMgr.ResmgrCmd.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.resourceMgr.ResmgrMsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponsequeue(value);
      break;
    case 3:
      var value = new proto.resourceMgr.CmdSendRequest;
      reader.readMessage(value,proto.resourceMgr.CmdSendRequest.deserializeBinaryFromReader);
      msg.setCmdsendrequest(value);
      break;
    case 4:
      var value = new proto.resourceMgr.CmdReserveResource;
      reader.readMessage(value,proto.resourceMgr.CmdReserveResource.deserializeBinaryFromReader);
      msg.setCmdreserveresource(value);
      break;
    case 5:
      var value = new proto.resourceMgr.CmdUpdateStatus;
      reader.readMessage(value,proto.resourceMgr.CmdUpdateStatus.deserializeBinaryFromReader);
      msg.setCmdupdatestatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.ResmgrCmd.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.ResmgrCmd.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.ResmgrCmd} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.ResmgrCmd.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getResponsequeue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCmdsendrequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.resourceMgr.CmdSendRequest.serializeBinaryToWriter
    );
  }
  f = message.getCmdreserveresource();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.resourceMgr.CmdReserveResource.serializeBinaryToWriter
    );
  }
  f = message.getCmdupdatestatus();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.resourceMgr.CmdUpdateStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResmgrMsgType msgType = 1;
 * @return {!proto.resourceMgr.ResmgrMsgType}
 */
proto.resourceMgr.ResmgrCmd.prototype.getMsgtype = function() {
  return /** @type {!proto.resourceMgr.ResmgrMsgType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.resourceMgr.ResmgrMsgType} value
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
 */
proto.resourceMgr.ResmgrCmd.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string responseQueue = 2;
 * @return {string}
 */
proto.resourceMgr.ResmgrCmd.prototype.getResponsequeue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
 */
proto.resourceMgr.ResmgrCmd.prototype.setResponsequeue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CmdSendRequest cmdSendRequest = 3;
 * @return {?proto.resourceMgr.CmdSendRequest}
 */
proto.resourceMgr.ResmgrCmd.prototype.getCmdsendrequest = function() {
  return /** @type{?proto.resourceMgr.CmdSendRequest} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdSendRequest, 3));
};


/**
 * @param {?proto.resourceMgr.CmdSendRequest|undefined} value
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
*/
proto.resourceMgr.ResmgrCmd.prototype.setCmdsendrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.resourceMgr.ResmgrCmd.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
 */
proto.resourceMgr.ResmgrCmd.prototype.clearCmdsendrequest = function() {
  return this.setCmdsendrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrCmd.prototype.hasCmdsendrequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CmdReserveResource cmdReserveResource = 4;
 * @return {?proto.resourceMgr.CmdReserveResource}
 */
proto.resourceMgr.ResmgrCmd.prototype.getCmdreserveresource = function() {
  return /** @type{?proto.resourceMgr.CmdReserveResource} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdReserveResource, 4));
};


/**
 * @param {?proto.resourceMgr.CmdReserveResource|undefined} value
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
*/
proto.resourceMgr.ResmgrCmd.prototype.setCmdreserveresource = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.resourceMgr.ResmgrCmd.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
 */
proto.resourceMgr.ResmgrCmd.prototype.clearCmdreserveresource = function() {
  return this.setCmdreserveresource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrCmd.prototype.hasCmdreserveresource = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CmdUpdateStatus cmdUpdateStatus = 5;
 * @return {?proto.resourceMgr.CmdUpdateStatus}
 */
proto.resourceMgr.ResmgrCmd.prototype.getCmdupdatestatus = function() {
  return /** @type{?proto.resourceMgr.CmdUpdateStatus} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdUpdateStatus, 5));
};


/**
 * @param {?proto.resourceMgr.CmdUpdateStatus|undefined} value
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
*/
proto.resourceMgr.ResmgrCmd.prototype.setCmdupdatestatus = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.resourceMgr.ResmgrCmd.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrCmd} returns this
 */
proto.resourceMgr.ResmgrCmd.prototype.clearCmdupdatestatus = function() {
  return this.setCmdupdatestatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrCmd.prototype.hasCmdupdatestatus = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resourceMgr.ResmgrRsp.oneofGroups_ = [[3,4,5]];

/**
 * @enum {number}
 */
proto.resourceMgr.ResmgrRsp.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  RSPSENDREQUEST: 3,
  RSPRESERVERESOURCE: 4,
  RSPUPDATESTATUS: 5
};

/**
 * @return {proto.resourceMgr.ResmgrRsp.PayloadCase}
 */
proto.resourceMgr.ResmgrRsp.prototype.getPayloadCase = function() {
  return /** @type {proto.resourceMgr.ResmgrRsp.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.resourceMgr.ResmgrRsp.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.ResmgrRsp.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.ResmgrRsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.ResmgrRsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.ResmgrRsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rspsendrequest: (f = msg.getRspsendrequest()) && proto.resourceMgr.RspSendRequest.toObject(includeInstance, f),
    rspreserveresource: (f = msg.getRspreserveresource()) && proto.resourceMgr.RspReserveResource.toObject(includeInstance, f),
    rspupdatestatus: (f = msg.getRspupdatestatus()) && proto.resourceMgr.RspUpdateStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.ResmgrRsp}
 */
proto.resourceMgr.ResmgrRsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.ResmgrRsp;
  return proto.resourceMgr.ResmgrRsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.ResmgrRsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.ResmgrRsp}
 */
proto.resourceMgr.ResmgrRsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.resourceMgr.ResmgrMsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 3:
      var value = new proto.resourceMgr.RspSendRequest;
      reader.readMessage(value,proto.resourceMgr.RspSendRequest.deserializeBinaryFromReader);
      msg.setRspsendrequest(value);
      break;
    case 4:
      var value = new proto.resourceMgr.RspReserveResource;
      reader.readMessage(value,proto.resourceMgr.RspReserveResource.deserializeBinaryFromReader);
      msg.setRspreserveresource(value);
      break;
    case 5:
      var value = new proto.resourceMgr.RspUpdateStatus;
      reader.readMessage(value,proto.resourceMgr.RspUpdateStatus.deserializeBinaryFromReader);
      msg.setRspupdatestatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.ResmgrRsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.ResmgrRsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.ResmgrRsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.ResmgrRsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRspsendrequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.resourceMgr.RspSendRequest.serializeBinaryToWriter
    );
  }
  f = message.getRspreserveresource();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.resourceMgr.RspReserveResource.serializeBinaryToWriter
    );
  }
  f = message.getRspupdatestatus();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.resourceMgr.RspUpdateStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResmgrMsgType msgType = 1;
 * @return {!proto.resourceMgr.ResmgrMsgType}
 */
proto.resourceMgr.ResmgrRsp.prototype.getMsgtype = function() {
  return /** @type {!proto.resourceMgr.ResmgrMsgType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.resourceMgr.ResmgrMsgType} value
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
 */
proto.resourceMgr.ResmgrRsp.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional RspSendRequest rspSendRequest = 3;
 * @return {?proto.resourceMgr.RspSendRequest}
 */
proto.resourceMgr.ResmgrRsp.prototype.getRspsendrequest = function() {
  return /** @type{?proto.resourceMgr.RspSendRequest} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspSendRequest, 3));
};


/**
 * @param {?proto.resourceMgr.RspSendRequest|undefined} value
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
*/
proto.resourceMgr.ResmgrRsp.prototype.setRspsendrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.resourceMgr.ResmgrRsp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
 */
proto.resourceMgr.ResmgrRsp.prototype.clearRspsendrequest = function() {
  return this.setRspsendrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrRsp.prototype.hasRspsendrequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RspReserveResource rspReserveResource = 4;
 * @return {?proto.resourceMgr.RspReserveResource}
 */
proto.resourceMgr.ResmgrRsp.prototype.getRspreserveresource = function() {
  return /** @type{?proto.resourceMgr.RspReserveResource} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspReserveResource, 4));
};


/**
 * @param {?proto.resourceMgr.RspReserveResource|undefined} value
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
*/
proto.resourceMgr.ResmgrRsp.prototype.setRspreserveresource = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.resourceMgr.ResmgrRsp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
 */
proto.resourceMgr.ResmgrRsp.prototype.clearRspreserveresource = function() {
  return this.setRspreserveresource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrRsp.prototype.hasRspreserveresource = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional RspUpdateStatus rspUpdateStatus = 5;
 * @return {?proto.resourceMgr.RspUpdateStatus}
 */
proto.resourceMgr.ResmgrRsp.prototype.getRspupdatestatus = function() {
  return /** @type{?proto.resourceMgr.RspUpdateStatus} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspUpdateStatus, 5));
};


/**
 * @param {?proto.resourceMgr.RspUpdateStatus|undefined} value
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
*/
proto.resourceMgr.ResmgrRsp.prototype.setRspupdatestatus = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.resourceMgr.ResmgrRsp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resourceMgr.ResmgrRsp} returns this
 */
proto.resourceMgr.ResmgrRsp.prototype.clearRspupdatestatus = function() {
  return this.setRspupdatestatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resourceMgr.ResmgrRsp.prototype.hasRspupdatestatus = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdSendRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdSendRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdSendRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdSendRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    reserveresource: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    request: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdSendRequest}
 */
proto.resourceMgr.CmdSendRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdSendRequest;
  return proto.resourceMgr.CmdSendRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdSendRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdSendRequest}
 */
proto.resourceMgr.CmdSendRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReserveresource(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdSendRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.CmdSendRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdSendRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdSendRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReserveresource();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRequest();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string clientId = 1;
 * @return {string}
 */
proto.resourceMgr.CmdSendRequest.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.CmdSendRequest} returns this
 */
proto.resourceMgr.CmdSendRequest.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool reserveResource = 2;
 * @return {boolean}
 */
proto.resourceMgr.CmdSendRequest.prototype.getReserveresource = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.resourceMgr.CmdSendRequest} returns this
 */
proto.resourceMgr.CmdSendRequest.prototype.setReserveresource = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string request = 3;
 * @return {string}
 */
proto.resourceMgr.CmdSendRequest.prototype.getRequest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.CmdSendRequest} returns this
 */
proto.resourceMgr.CmdSendRequest.prototype.setRequest = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspSendRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspSendRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspSendRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspSendRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    errcode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errmsg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    response: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspSendRequest}
 */
proto.resourceMgr.RspSendRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspSendRequest;
  return proto.resourceMgr.RspSendRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspSendRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspSendRequest}
 */
proto.resourceMgr.RspSendRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setErrcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspSendRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.RspSendRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspSendRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspSendRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrcode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResponse();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 errCode = 1;
 * @return {number}
 */
proto.resourceMgr.RspSendRequest.prototype.getErrcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.resourceMgr.RspSendRequest} returns this
 */
proto.resourceMgr.RspSendRequest.prototype.setErrcode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string errMsg = 2;
 * @return {string}
 */
proto.resourceMgr.RspSendRequest.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.RspSendRequest} returns this
 */
proto.resourceMgr.RspSendRequest.prototype.setErrmsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string response = 3;
 * @return {string}
 */
proto.resourceMgr.RspSendRequest.prototype.getResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.RspSendRequest} returns this
 */
proto.resourceMgr.RspSendRequest.prototype.setResponse = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdReserveResource.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdReserveResource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdReserveResource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdReserveResource.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    request: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdReserveResource}
 */
proto.resourceMgr.CmdReserveResource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdReserveResource;
  return proto.resourceMgr.CmdReserveResource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdReserveResource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdReserveResource}
 */
proto.resourceMgr.CmdReserveResource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdReserveResource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.CmdReserveResource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdReserveResource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdReserveResource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRequest();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string clientId = 1;
 * @return {string}
 */
proto.resourceMgr.CmdReserveResource.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.CmdReserveResource} returns this
 */
proto.resourceMgr.CmdReserveResource.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string request = 2;
 * @return {string}
 */
proto.resourceMgr.CmdReserveResource.prototype.getRequest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.CmdReserveResource} returns this
 */
proto.resourceMgr.CmdReserveResource.prototype.setRequest = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspReserveResource.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspReserveResource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspReserveResource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspReserveResource.toObject = function(includeInstance, msg) {
  var f, obj = {
    errcode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errmsg: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspReserveResource}
 */
proto.resourceMgr.RspReserveResource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspReserveResource;
  return proto.resourceMgr.RspReserveResource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspReserveResource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspReserveResource}
 */
proto.resourceMgr.RspReserveResource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setErrcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspReserveResource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.RspReserveResource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspReserveResource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspReserveResource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrcode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 errCode = 1;
 * @return {number}
 */
proto.resourceMgr.RspReserveResource.prototype.getErrcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.resourceMgr.RspReserveResource} returns this
 */
proto.resourceMgr.RspReserveResource.prototype.setErrcode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string errMsg = 2;
 * @return {string}
 */
proto.resourceMgr.RspReserveResource.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.RspReserveResource} returns this
 */
proto.resourceMgr.RspReserveResource.prototype.setErrmsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdUpdateStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdUpdateStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdUpdateStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdUpdateStatus.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdUpdateStatus}
 */
proto.resourceMgr.CmdUpdateStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdUpdateStatus;
  return proto.resourceMgr.CmdUpdateStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdUpdateStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdUpdateStatus}
 */
proto.resourceMgr.CmdUpdateStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdUpdateStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.CmdUpdateStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdUpdateStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.CmdUpdateStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspUpdateStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspUpdateStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspUpdateStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspUpdateStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    errcode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errmsg: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspUpdateStatus}
 */
proto.resourceMgr.RspUpdateStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspUpdateStatus;
  return proto.resourceMgr.RspUpdateStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspUpdateStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspUpdateStatus}
 */
proto.resourceMgr.RspUpdateStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setErrcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspUpdateStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resourceMgr.RspUpdateStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspUpdateStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resourceMgr.RspUpdateStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrcode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 errCode = 1;
 * @return {number}
 */
proto.resourceMgr.RspUpdateStatus.prototype.getErrcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.resourceMgr.RspUpdateStatus} returns this
 */
proto.resourceMgr.RspUpdateStatus.prototype.setErrcode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string errMsg = 2;
 * @return {string}
 */
proto.resourceMgr.RspUpdateStatus.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resourceMgr.RspUpdateStatus} returns this
 */
proto.resourceMgr.RspUpdateStatus.prototype.setErrmsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.resourceMgr.ResmgrMsgType = {
  SENDREQUESTTYPE: 0,
  RESERVERESOURCETYPE: 1,
  UPDATESTATUSTYPE: 2
};

goog.object.extend(exports, proto.resourceMgr);
