/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.resourceMgr.CmdGetLayouts', null, global);
goog.exportSymbol('proto.resourceMgr.CmdGetLines', null, global);
goog.exportSymbol('proto.resourceMgr.CmdGetMachines', null, global);
goog.exportSymbol('proto.resourceMgr.FacdataCmd', null, global);
goog.exportSymbol('proto.resourceMgr.FacdataMsgType', null, global);
goog.exportSymbol('proto.resourceMgr.FacdataRsp', null, global);
goog.exportSymbol('proto.resourceMgr.RspGetLayouts', null, global);
goog.exportSymbol('proto.resourceMgr.RspGetLines', null, global);
goog.exportSymbol('proto.resourceMgr.RspGetMachines', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.FacdataCmd = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.resourceMgr.FacdataCmd.oneofGroups_);
};
goog.inherits(proto.resourceMgr.FacdataCmd, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.FacdataCmd.displayName = 'proto.resourceMgr.FacdataCmd';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resourceMgr.FacdataCmd.oneofGroups_ = [[4,5,6]];

/**
 * @enum {number}
 */
proto.resourceMgr.FacdataCmd.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  CMDGETLINES: 4,
  CMDGETMACHINES: 5,
  CMDGETLAYOUTS: 6
};

/**
 * @return {proto.resourceMgr.FacdataCmd.PayloadCase}
 */
proto.resourceMgr.FacdataCmd.prototype.getPayloadCase = function() {
  return /** @type {proto.resourceMgr.FacdataCmd.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.resourceMgr.FacdataCmd.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.FacdataCmd.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.FacdataCmd.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.FacdataCmd} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.FacdataCmd.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgtype: msg.getMsgtype(),
    responsequeue: msg.getResponsequeue(),
    cmdgetlines: (f = msg.getCmdgetlines()) && proto.resourceMgr.CmdGetLines.toObject(includeInstance, f),
    cmdgetmachines: (f = msg.getCmdgetmachines()) && proto.resourceMgr.CmdGetMachines.toObject(includeInstance, f),
    cmdgetlayouts: (f = msg.getCmdgetlayouts()) && proto.resourceMgr.CmdGetLayouts.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.FacdataCmd}
 */
proto.resourceMgr.FacdataCmd.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.FacdataCmd;
  return proto.resourceMgr.FacdataCmd.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.FacdataCmd} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.FacdataCmd}
 */
proto.resourceMgr.FacdataCmd.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.resourceMgr.FacdataMsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponsequeue(value);
      break;
    case 4:
      var value = new proto.resourceMgr.CmdGetLines;
      reader.readMessage(value,proto.resourceMgr.CmdGetLines.deserializeBinaryFromReader);
      msg.setCmdgetlines(value);
      break;
    case 5:
      var value = new proto.resourceMgr.CmdGetMachines;
      reader.readMessage(value,proto.resourceMgr.CmdGetMachines.deserializeBinaryFromReader);
      msg.setCmdgetmachines(value);
      break;
    case 6:
      var value = new proto.resourceMgr.CmdGetLayouts;
      reader.readMessage(value,proto.resourceMgr.CmdGetLayouts.deserializeBinaryFromReader);
      msg.setCmdgetlayouts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.FacdataCmd} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.FacdataCmd.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.FacdataCmd.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.FacdataCmd.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getResponsequeue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getCmdgetlines();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.resourceMgr.CmdGetLines.serializeBinaryToWriter
    );
  }
  f = this.getCmdgetmachines();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.resourceMgr.CmdGetMachines.serializeBinaryToWriter
    );
  }
  f = this.getCmdgetlayouts();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.resourceMgr.CmdGetLayouts.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.FacdataCmd} The clone.
 */
proto.resourceMgr.FacdataCmd.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.FacdataCmd} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional FacdataMsgType msgType = 1;
 * @return {!proto.resourceMgr.FacdataMsgType}
 */
proto.resourceMgr.FacdataCmd.prototype.getMsgtype = function() {
  return /** @type {!proto.resourceMgr.FacdataMsgType} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.resourceMgr.FacdataMsgType} value  */
proto.resourceMgr.FacdataCmd.prototype.setMsgtype = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string responseQueue = 2;
 * @return {string}
 */
proto.resourceMgr.FacdataCmd.prototype.getResponsequeue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.resourceMgr.FacdataCmd.prototype.setResponsequeue = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional CmdGetLines cmdGetLines = 4;
 * @return {proto.resourceMgr.CmdGetLines}
 */
proto.resourceMgr.FacdataCmd.prototype.getCmdgetlines = function() {
  return /** @type{proto.resourceMgr.CmdGetLines} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdGetLines, 4));
};


/** @param {proto.resourceMgr.CmdGetLines|undefined} value  */
proto.resourceMgr.FacdataCmd.prototype.setCmdgetlines = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.resourceMgr.FacdataCmd.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataCmd.prototype.clearCmdgetlines = function() {
  this.setCmdgetlines(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataCmd.prototype.hasCmdgetlines = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CmdGetMachines cmdGetMachines = 5;
 * @return {proto.resourceMgr.CmdGetMachines}
 */
proto.resourceMgr.FacdataCmd.prototype.getCmdgetmachines = function() {
  return /** @type{proto.resourceMgr.CmdGetMachines} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdGetMachines, 5));
};


/** @param {proto.resourceMgr.CmdGetMachines|undefined} value  */
proto.resourceMgr.FacdataCmd.prototype.setCmdgetmachines = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.resourceMgr.FacdataCmd.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataCmd.prototype.clearCmdgetmachines = function() {
  this.setCmdgetmachines(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataCmd.prototype.hasCmdgetmachines = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional CmdGetLayouts cmdGetLayouts = 6;
 * @return {proto.resourceMgr.CmdGetLayouts}
 */
proto.resourceMgr.FacdataCmd.prototype.getCmdgetlayouts = function() {
  return /** @type{proto.resourceMgr.CmdGetLayouts} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.CmdGetLayouts, 6));
};


/** @param {proto.resourceMgr.CmdGetLayouts|undefined} value  */
proto.resourceMgr.FacdataCmd.prototype.setCmdgetlayouts = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.resourceMgr.FacdataCmd.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataCmd.prototype.clearCmdgetlayouts = function() {
  this.setCmdgetlayouts(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataCmd.prototype.hasCmdgetlayouts = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.FacdataRsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.resourceMgr.FacdataRsp.oneofGroups_);
};
goog.inherits(proto.resourceMgr.FacdataRsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.FacdataRsp.displayName = 'proto.resourceMgr.FacdataRsp';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resourceMgr.FacdataRsp.oneofGroups_ = [[5,6,7]];

/**
 * @enum {number}
 */
proto.resourceMgr.FacdataRsp.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  RSPGETLINES: 5,
  RSPGETMACHINES: 6,
  RSPGETLAYOUTS: 7
};

/**
 * @return {proto.resourceMgr.FacdataRsp.PayloadCase}
 */
proto.resourceMgr.FacdataRsp.prototype.getPayloadCase = function() {
  return /** @type {proto.resourceMgr.FacdataRsp.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.resourceMgr.FacdataRsp.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.FacdataRsp.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.FacdataRsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.FacdataRsp} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.FacdataRsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgtype: msg.getMsgtype(),
    errcode: msg.getErrcode(),
    errmsg: msg.getErrmsg(),
    rspgetlines: (f = msg.getRspgetlines()) && proto.resourceMgr.RspGetLines.toObject(includeInstance, f),
    rspgetmachines: (f = msg.getRspgetmachines()) && proto.resourceMgr.RspGetMachines.toObject(includeInstance, f),
    rspgetlayouts: (f = msg.getRspgetlayouts()) && proto.resourceMgr.RspGetLayouts.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.FacdataRsp}
 */
proto.resourceMgr.FacdataRsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.FacdataRsp;
  return proto.resourceMgr.FacdataRsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.FacdataRsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.FacdataRsp}
 */
proto.resourceMgr.FacdataRsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.resourceMgr.FacdataMsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setErrcode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    case 5:
      var value = new proto.resourceMgr.RspGetLines;
      reader.readMessage(value,proto.resourceMgr.RspGetLines.deserializeBinaryFromReader);
      msg.setRspgetlines(value);
      break;
    case 6:
      var value = new proto.resourceMgr.RspGetMachines;
      reader.readMessage(value,proto.resourceMgr.RspGetMachines.deserializeBinaryFromReader);
      msg.setRspgetmachines(value);
      break;
    case 7:
      var value = new proto.resourceMgr.RspGetLayouts;
      reader.readMessage(value,proto.resourceMgr.RspGetLayouts.deserializeBinaryFromReader);
      msg.setRspgetlayouts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.FacdataRsp} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.FacdataRsp.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.FacdataRsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.FacdataRsp.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getErrcode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getRspgetlines();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.resourceMgr.RspGetLines.serializeBinaryToWriter
    );
  }
  f = this.getRspgetmachines();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.resourceMgr.RspGetMachines.serializeBinaryToWriter
    );
  }
  f = this.getRspgetlayouts();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.resourceMgr.RspGetLayouts.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.FacdataRsp} The clone.
 */
proto.resourceMgr.FacdataRsp.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.FacdataRsp} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional FacdataMsgType msgType = 1;
 * @return {!proto.resourceMgr.FacdataMsgType}
 */
proto.resourceMgr.FacdataRsp.prototype.getMsgtype = function() {
  return /** @type {!proto.resourceMgr.FacdataMsgType} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.resourceMgr.FacdataMsgType} value  */
proto.resourceMgr.FacdataRsp.prototype.setMsgtype = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 errCode = 2;
 * @return {number}
 */
proto.resourceMgr.FacdataRsp.prototype.getErrcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.resourceMgr.FacdataRsp.prototype.setErrcode = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string errMsg = 3;
 * @return {string}
 */
proto.resourceMgr.FacdataRsp.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.resourceMgr.FacdataRsp.prototype.setErrmsg = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional RspGetLines rspGetLines = 5;
 * @return {proto.resourceMgr.RspGetLines}
 */
proto.resourceMgr.FacdataRsp.prototype.getRspgetlines = function() {
  return /** @type{proto.resourceMgr.RspGetLines} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspGetLines, 5));
};


/** @param {proto.resourceMgr.RspGetLines|undefined} value  */
proto.resourceMgr.FacdataRsp.prototype.setRspgetlines = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.resourceMgr.FacdataRsp.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataRsp.prototype.clearRspgetlines = function() {
  this.setRspgetlines(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataRsp.prototype.hasRspgetlines = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional RspGetMachines rspGetMachines = 6;
 * @return {proto.resourceMgr.RspGetMachines}
 */
proto.resourceMgr.FacdataRsp.prototype.getRspgetmachines = function() {
  return /** @type{proto.resourceMgr.RspGetMachines} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspGetMachines, 6));
};


/** @param {proto.resourceMgr.RspGetMachines|undefined} value  */
proto.resourceMgr.FacdataRsp.prototype.setRspgetmachines = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.resourceMgr.FacdataRsp.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataRsp.prototype.clearRspgetmachines = function() {
  this.setRspgetmachines(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataRsp.prototype.hasRspgetmachines = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional RspGetLayouts rspGetLayouts = 7;
 * @return {proto.resourceMgr.RspGetLayouts}
 */
proto.resourceMgr.FacdataRsp.prototype.getRspgetlayouts = function() {
  return /** @type{proto.resourceMgr.RspGetLayouts} */ (
    jspb.Message.getWrapperField(this, proto.resourceMgr.RspGetLayouts, 7));
};


/** @param {proto.resourceMgr.RspGetLayouts|undefined} value  */
proto.resourceMgr.FacdataRsp.prototype.setRspgetlayouts = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.resourceMgr.FacdataRsp.oneofGroups_[0], value);
};


proto.resourceMgr.FacdataRsp.prototype.clearRspgetlayouts = function() {
  this.setRspgetlayouts(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.resourceMgr.FacdataRsp.prototype.hasRspgetlayouts = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdGetLines = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdGetLines, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.CmdGetLines.displayName = 'proto.resourceMgr.CmdGetLines';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdGetLines.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdGetLines.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdGetLines} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.CmdGetLines.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdGetLines}
 */
proto.resourceMgr.CmdGetLines.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdGetLines;
  return proto.resourceMgr.CmdGetLines.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdGetLines} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdGetLines}
 */
proto.resourceMgr.CmdGetLines.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdGetLines} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetLines.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdGetLines.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetLines.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.CmdGetLines} The clone.
 */
proto.resourceMgr.CmdGetLines.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.CmdGetLines} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspGetLines = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspGetLines, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.RspGetLines.displayName = 'proto.resourceMgr.RspGetLines';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspGetLines.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspGetLines.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspGetLines} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.RspGetLines.toObject = function(includeInstance, msg) {
  var f, obj = {
    lines: msg.getLines()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspGetLines}
 */
proto.resourceMgr.RspGetLines.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspGetLines;
  return proto.resourceMgr.RspGetLines.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspGetLines} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspGetLines}
 */
proto.resourceMgr.RspGetLines.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLines(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspGetLines} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetLines.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspGetLines.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetLines.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getLines();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.RspGetLines} The clone.
 */
proto.resourceMgr.RspGetLines.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.RspGetLines} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string lines = 1;
 * @return {string}
 */
proto.resourceMgr.RspGetLines.prototype.getLines = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.resourceMgr.RspGetLines.prototype.setLines = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdGetMachines = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdGetMachines, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.CmdGetMachines.displayName = 'proto.resourceMgr.CmdGetMachines';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdGetMachines.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdGetMachines.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdGetMachines} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.CmdGetMachines.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdGetMachines}
 */
proto.resourceMgr.CmdGetMachines.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdGetMachines;
  return proto.resourceMgr.CmdGetMachines.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdGetMachines} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdGetMachines}
 */
proto.resourceMgr.CmdGetMachines.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdGetMachines} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetMachines.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdGetMachines.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetMachines.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.CmdGetMachines} The clone.
 */
proto.resourceMgr.CmdGetMachines.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.CmdGetMachines} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspGetMachines = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspGetMachines, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.RspGetMachines.displayName = 'proto.resourceMgr.RspGetMachines';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspGetMachines.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspGetMachines.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspGetMachines} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.RspGetMachines.toObject = function(includeInstance, msg) {
  var f, obj = {
    machines: msg.getMachines()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspGetMachines}
 */
proto.resourceMgr.RspGetMachines.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspGetMachines;
  return proto.resourceMgr.RspGetMachines.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspGetMachines} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspGetMachines}
 */
proto.resourceMgr.RspGetMachines.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMachines(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspGetMachines} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetMachines.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspGetMachines.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetMachines.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMachines();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.RspGetMachines} The clone.
 */
proto.resourceMgr.RspGetMachines.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.RspGetMachines} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string machines = 1;
 * @return {string}
 */
proto.resourceMgr.RspGetMachines.prototype.getMachines = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.resourceMgr.RspGetMachines.prototype.setMachines = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.CmdGetLayouts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.CmdGetLayouts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.CmdGetLayouts.displayName = 'proto.resourceMgr.CmdGetLayouts';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.CmdGetLayouts.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.CmdGetLayouts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.CmdGetLayouts} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.CmdGetLayouts.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.CmdGetLayouts}
 */
proto.resourceMgr.CmdGetLayouts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.CmdGetLayouts;
  return proto.resourceMgr.CmdGetLayouts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.CmdGetLayouts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.CmdGetLayouts}
 */
proto.resourceMgr.CmdGetLayouts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.CmdGetLayouts} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetLayouts.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.CmdGetLayouts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.CmdGetLayouts.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.CmdGetLayouts} The clone.
 */
proto.resourceMgr.CmdGetLayouts.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.CmdGetLayouts} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resourceMgr.RspGetLayouts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resourceMgr.RspGetLayouts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.resourceMgr.RspGetLayouts.displayName = 'proto.resourceMgr.RspGetLayouts';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resourceMgr.RspGetLayouts.prototype.toObject = function(opt_includeInstance) {
  return proto.resourceMgr.RspGetLayouts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resourceMgr.RspGetLayouts} msg The msg instance to transform.
 * @return {!Object}
 */
proto.resourceMgr.RspGetLayouts.toObject = function(includeInstance, msg) {
  var f, obj = {
    layouts: msg.getLayouts()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resourceMgr.RspGetLayouts}
 */
proto.resourceMgr.RspGetLayouts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resourceMgr.RspGetLayouts;
  return proto.resourceMgr.RspGetLayouts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resourceMgr.RspGetLayouts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resourceMgr.RspGetLayouts}
 */
proto.resourceMgr.RspGetLayouts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLayouts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.resourceMgr.RspGetLayouts} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetLayouts.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resourceMgr.RspGetLayouts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.resourceMgr.RspGetLayouts.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getLayouts();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.resourceMgr.RspGetLayouts} The clone.
 */
proto.resourceMgr.RspGetLayouts.prototype.cloneMessage = function() {
  return /** @type {!proto.resourceMgr.RspGetLayouts} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string layouts = 1;
 * @return {string}
 */
proto.resourceMgr.RspGetLayouts.prototype.getLayouts = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.resourceMgr.RspGetLayouts.prototype.setLayouts = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.resourceMgr.FacdataMsgType = {
  NOTYPE: 0,
  GETLINESTYPE: 1,
  GETMACHINESTYPE: 2,
  GETLAYOUTSTYPE: 3
};

goog.object.extend(exports, proto.resourceMgr);
